image: maven

stages:
  - analyze
  - validate
  - test

checkstyle_analysis:
  stage: validate
  script: mvn -Dtestfx.robot=glass -Dtestfx.headless=true -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw test

sonar_analysis:
  stage: analyze
  script:
    - java -version
    - mvn -version
    - |
      mvn -X sonar:sonar \
      -Dsonar.host.url=http://coursework.cs.duke.edu:9000 \
      -Dsonar.sources=src -Dsonar.java.binaries=. \
      -Dsonar.exclusions=**/*.xml,**/*.css,**/test/**
  tags:
    - sonarqube
  only:
    - master

java_testing:
  stage: test
  script:
    - mvn -DargLine= verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

